# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - DLPInstitutional

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://dlpcontainer1.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_eedc9c468bf846299738a4dc35e7b2f5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e2871d07eac547ec969b61aef1273921 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: dlpcontainer1.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_eedc9c468bf846299738a4dc35e7b2f5 }}/app-dev:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'DLPInstitutional'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_277e5c770b134de789e7c19c9d5fdc43 }}
        images: 'dlpcontainer1.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_eedc9c468bf846299738a4dc35e7b2f5 }}/app-dev:${{ github.sha }}'